<?php

namespace Database\Seeders;

use App\Models\Package;
use Illuminate\Database\Seeder;
use Faker\Factory as Faker;

class PackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create();

        Package::insert([
            [
                'name_ar'           => 'الباقة السنوية',
                'name_en'           => 'Annual Package',
                'price'             => '120',
                'discount'          => '60',
                'duration_ar'       => 'سنوي',
                'duration_en'       => 'Annual',
                'duration_time'     => '365',
                'description_ar'    => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة لقد تم توليد هذا النص من مولد النص العربى :',
                'description_en'    => 'This is a sample text to be replaced in the same space of the text generated by the Arabic text generator.',
                'badge'             => '1.png',
                'keyword_ar'        => 'القيمة الأفضل',
                'keyword_en'        => 'Best Value',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'name_ar'           => 'باقة 3 شهور',
                'name_en'           => '3 Month Package',
                'duration_time'     => '90',
                'price'             => '30',
                'discount'          => '6',
                'duration_ar'       => 'شهري',
                'duration_en'       => 'Monthly',
                'description_ar'    => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة لقد تم توليد هذا النص من مولد النص العربى :',
                'description_en'    => 'This is a sample text to be replaced in the same space of the text generated by the Arabic text generator.',
                'badge'             => '1.png',
                'keyword_ar'        => 'الأكثر شيوعاً',
                'keyword_en'        => 'Most Popular',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'name_ar'           => 'باقة شهر واحد',
                'name_en'           => 'Monthly Package',
                'duration_time'     => '30',
                'price'             => '9',
                'discount'          => '1',
                'duration_ar'       => 'شهر واحد',
                'duration_en'       => 'Monthly',
                'description_ar'    => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة لقد تم توليد هذا النص من مولد النص العربى :',
                'description_en'    => 'This is a sample text to be replaced in the same space of the text generated by the Arabic text generator.',
                'badge'             => '1.png',
                'keyword_ar'        => '',
                'keyword_en'        => '',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
        ]);
    }
}
